#!/bin/bash

export DATA=/eos/cms/store/group/dpg_mtd/comm_mtd/TB/MTDTB_T10_May2018/raw/DataTree/

touch list.txt


cd $DATA

for((i=83;$i<=89;i=$(($i+1)))); do
  export NAME=114$i
  
  for((j=1;j<50;j=$(($j+1)))); do
      
      if [ $j -le 9 ]; then
	  k="0"$j
      else
	  k=$j
      fi
      
      if [ -f $DATA$NAME/"00"$k.root ]
      then
	  
	  cp $DATA$NAME/"00"$k.root ~/Files/"00"$k$NAME.root	  
	  
	  echo "00"$k$NAME.root >> list.txt
	 	  
	  #echo $DATA$NAME/"00"$k.root 
	  #echo ~/Files/"00"$k$NAME.root
      fi
      
  done
done

exit 0

case
